# Generated by Django 5.2.7 on 2025-10-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blof',
            new_name='Blog',
        ),
    ]
