# Generated by Django 5.2.7 on 2025-10-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_blog_title_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
